export {default as Header} from "./Header/Header";
export {default as Navbar} from './Navbar/Navbar';
export {default as Welcome} from './Welcome/Welcome';
export {default as About} from './About/About';
export {default as Join} from './Join/Join';
export {default as Roadmap} from './Roadmap/RoadMap';
export {default as Benefits} from './Benefits/Benefits';
export {default as Team} from './Team/Team';
export {default as Faq} from './Faq/Faq';
